# Generated by c.py
# Atul Varma (Spring 2004)

    .text
fib:
  pushl %ebp
  movl %esp, %ebp
  leal stuff_count, %edx
  addl $1, (%edx)
  movl (%edx), %ecx
  movl %ecx, %eax
  jmp .L0_function_end
.L0_function_end:
  movl %ebp, %esp
  popl %ebp
  ret

    .global increment_stuff_count
increment_stuff_count:
  pushl %ebp
  movl %esp, %ebp
  call fib
  movl $0, %eax
  jmp .L1_function_end
.L1_function_end:
  movl %ebp, %esp
  popl %ebp
  ret

.global_vars:
  .comm stuff_count,16

